# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build_test:
    docker:
      # specify the version
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/rodellison/alexa-slick-dealer
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: make test  #the Makefile test command performs both build and test
      - persist_to_workspace:
          root: bin
          paths:
            - '*'

  deploy:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/rodellison/alexa-slick-dealer
    steps:
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      - attach_workspace:
          at: /go/src/github.com/rodellison/alexa-slick-dealer/workspace
      - run: ls /go/src/github.com/rodellison/alexa-slick-dealer/workspace/apl_template_export.json
      - run:
          name: Deploy application
          command: sls deploy --stage dev

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test
#      - deploy:
#          requires:
#            - build_test
